language: cpp
compiler:
  - clang
before_script:
  - sudo add-apt-repository -y ppa:apokluda/boost1.53 # Boost 1.53
  - sudo apt-get -qq update
  - sudo apt-get -qq install boost1.53
  - sudo apt-get install libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew1.5-dev libjpeg8-dev libsndfile1-dev libopenal-dev
  - cmake .
script: 
  - make -j4